In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from joblib import dump

#### Escalar solo el dataset de entrenamiento

In [2]:
df_data = pd.read_csv("process_dataset/train_data.csv")
df_data

,Age,Sex,Cholesterol,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,...,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Systolic,Diastolic
0,87,0,334,45,1,0,1,0,0,13.960410,...,223411,28.760947,69,4,4,7,3,0,102,73
1,52,1,292,102,0,0,1,1,1,0.633037,...,104146,27.012530,593,3,9,18,4,0,176,77
2,88,1,400,79,0,0,1,1,1,17.636194,...,86537,21.222328,674,2,7,6,3,0,121,92
3,43,1,267,86,1,1,1,1,0,4.484297,...,260229,30.271479,175,5,9,18,4,0,100,74
4,59,1,358,66,1,0,1,0,0,12.252802,...,37018,35.726888,99,7,9,0,5,1,129,110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6303,79,1,149,88,0,1,1,1,0,18.273681,...,20264,18.718850,222,4,10,11,2,1,96,60
6304,29,1,333,52,1,1,1,0,1,2.423985,...,285226,28.076361,673,2,6,6,3,0,104,81
6305,55,1,167,97,1,0,1,0,1,1.390657,...,232139,31.191200,601,5,4,6,3,0,107,74
6306,86,0,157,97,1,1,1,1,0,8.263862,...,163271,29.116222,35,5,10,17,3,0,132,89
6307,42,1,127,62,0,1,1,0,0,19.122234,...,41757,24.128094,559,2,7,15,3,1,93,64

#### FunciÃ³n para guardar escaladores y datos escalados

In [3]:
def save_scaler(df_data, scaler_instance, type_scaler):
    scaler_instance.fit(X=df_data.values)
    data_scaled = scaler_instance.transform(X=df_data.values)
    df_scaled = pd.DataFrame(data=data_scaled, columns=df_data.columns)
    df_scaled.to_csv(f"process_dataset/train_data_scaled_{type_scaler}.csv", index=False)
    dump(scaler_instance, f"results/scaler_{type_scaler}.joblib")

#### Escalar los datos con Standard Scaler

In [4]:
standard_scaler_instance = StandardScaler()
save_scaler(df_data, standard_scaler_instance, "standard")

#### Escalar los datos con MinMax Scaler

In [5]:
min_max_scaler_instance = MinMaxScaler()
save_scaler(df_data, min_max_scaler_instance, "min_max")

#### Escalar los datos con Robust Scaler

In [6]:
robust_scaler_instance = RobustScaler()
save_scaler(df_data, robust_scaler_instance, "robust")